sudo: false
language: java
jdk:
- openjdk11
script:
- mvn verify
cache:
  directories:
  - "$HOME/.m2/repository/"
# Taken in part from https://github.com/jvican/sbt-release-early/wiki/How-to-release-in-Travis-(CI)
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [[ "$TRAVIS_TAG" = v* ]]; then
    openssl aes-256-cbc -K $encrypted_352da9e6f448_key -iv $encrypted_352da9e6f448_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar -d tar xv -C travis -f travis/local.secrets.tar;
  fi
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [[ "$TRAVIS_TAG" = v* ]]; then
    # Tests are run as part of the script.
    mvn -q -Prelease gpg-maven-plugin:sign deploy -DskipTests --settings settings.xml
  fi
env:
  global:
  - secure: mMsRGGivOOeA8iTT1l7MJcx6U/kSnYkZGsFVid0pdMweskrxXbcgiClzPp29LiiOWi5X+zoAYVAFYKxU+Gb3BewQ57hFanjOS97oizqe6oLjuC5qJwlZ/9AXNb+9eaQiXN2AAWecHCO8UhLhNrEPlvfhX7wp5CuyavdmC5J76yTPvghtU3npJMOMCTfCaoMknZJ+tUPzKRPlunwVS2mIo2o8fn8rcMh3hQwrZRdu3lFyHMuuGnMdJ4MtSikjvYsYl0AtYpnlbuV3BIh4ugKlhkMl/fa3y8RS+OuBm8uitCkS1I58fNH3AjXGVHMsD/7YNvGzAHApdp426Ugzl7oZdwn/vnPm+kItMufnsSgK4l6768ab+xjuT01lfdAgqCmLuV9/IHtpUIxiZMkhJ2/3ug1JHuPziKWld4tp1gsWo2/Mc/i8x4SWfagUsDCCmcpiRLw4fOFPU3BRwb2nXsmwkRQxdiJwYso3xPL1q0rorv772XYkCAqwQI7tfNPTQ4pnpgZmaXxgWdiGFSnjfbw+rmURdGZ58Z9a7YEXCPpaVTT4Y/z2jF+12+v7YL1W4XV+5/3fCR2YYegjgyX1vZE0JP5gPIr7dLtDwD/Z64Vshg14VfJYecAlaTLx0peClf8u0M/CWqunv/xbApdEWCCP8TIdyvnVcOdpHC1TqjNkMKU=
  - secure: RJlgx6U1wZjjyajvx0owBNt0ggV2RJTNvPR6OcYCkhdFlOenOB5S3pRkLLNwudK32Y8pCRl+29h7uylsgF3bhHOpi8CTeTM+lSx4wzsfnLQZtt+s7aEXgqK+X5X4BAnrP8k3qsgYczuXOj2zEOGs5IDvdStqz/E4/gDaIeVYf9UAxe/HNzVxGLcvf/QP5TF5LBotQM2G9Nq+y/zuZ+GWgCmxpvbdoljHZPGxo3wei86FecRY125enSQYWUOnK/DTZkl2upq8fGZm6eJpBLZ6997F2Yn1zmiNK92+C35f9XjQMXzI+XJJnMcSkRv0qP9q1LnmrTX6ffBgVXMgxdMQYvu6OZX/jbUGzT8ut/HFW81Aq+r3FuNbiPrUrweeaMdYeAf632OFECqpejgPOMM53+3b3DmSq+sWesAlUbPq+hc7vEen8U/C4wjERz+eqPEdgTNs32pV2NxIKeejDuTZsR78goGPaDCiD3lof4lddg1RQEnAQxcis+0lapSVHaZKAu93CHYmeov/sBJ45iKEGWGPZ38BtROYcKpdfMhuGAF1+IDMH/m+PfpurQghylTRjEEog8cg5BSjlFDkLPi2k2RPMHoxxrwU1ROLyQ3B0lODY9GWvmGCaac6d7CDR4gSkEg/xOE9Zahv4FyW/peLjKpWymQBtKsMExlaKv6ttug=
  - secure: MwmQyqRk3VqvjVVBuN8eK8zJIrYDFmin+3TJXNEdd/CFu2iO6tifDbhiTohMYnkO9XPsv5HPCN94gopCWvx/nq8vSFYedfyLp4xusxc30E7Yoyfiu7FZ8x/iU9yUQDHZOMKyqoAOWTkWIdL4ryd4prf4gapHrh7CTB+5IUsVCuxXVqVZNZf3Gt51CwNNnVw8MIbdVYe8SsRAFOurPsoo7+Pjgz4ZUSHOAo88FkLCPhgfdv0vGwt8lfBC3p5StImsODMxPpqvXzfYX0dL9NJR65qUEc7gOrSI2LVqHwPP2TIdfGo1Pe8uY7yq+kGwKGWwv1lYwiDSf6pn3lyOkeC3IoBvGfjaop/tQqLB+eKkPWtApAGaYw0PqDYrPEGJ+cSdt3ZXIkyVRWAIrI5LTS1vVEdad4uoAeHsVjwxTA4ArLSOeNkVx4Vj43KIqc20ZAXOf0ut3SiagEWy7rXlkOrj47fVRrRDwh72tS3Cftn71X0kY5Y3lPCGCTJflCkHlPzyzlf/xm+VC2jJVwO9BbWKS/Ze9rQeok8nTcbn16kQAD8Z/zDtfPLOO7fgKxfPbUZc+5y02nPAh10jLH79Df1NdiLy8IvrWr1M4fCcivdkqah9Jw6l0bFuX+TClcGgvw8AWCBbcNRH2Py/ch0ax2qI0maoc2Bi1MIMYlurwxwP/l0=
